
(ert-deftest pacmacs--make-canvas-test ()
  (let* ((width 80)
         (height 120)
         (grid-width (/ width pacmacs--canvas-tile-width))
         (grid-height (/ height pacmacs--canvas-tile-height))
         (canvas (pacmacs--make-canvas 80 120)))
    (should canvas)
    (should (equal width (pacmacs--canvas-width canvas)))
    (should (equal height (pacmacs--canvas-height canvas)))
    (should (equal grid-width (pacmacs--canvas-grid-width canvas)))
    (should (equal grid-height (pacmacs--canvas-grid-height canvas))))
  (should-error (pacmacs--make-canvase 40 41)))

(ert-deftest pacmacs--make-tiles-grid-test ()
  (let* ((grid-width 2)
         (grid-height 3)
         (grid (pacmacs--make-tiles-grid grid-width
                                         grid-height)))
    (should (= grid-height (length grid)))
    (dotimes (i grid-height)
      (should (= grid-width (length (aref grid i)))))
    (dotimes (row grid-height)
      (dotimes (column grid-width)
        (let ((tile (aref (aref grid row) column)))
          (should (= pacmacs--canvas-tile-width (pacmacs--image-width tile)))
          (should (= pacmacs--canvas-tile-height (pacmacs--image-height tile))))))))
